-- =============================================
-- 旅館管理系統 - 員工模組
-- DEPARTMENT / JOB_TITLE / EMPLOYEE
-- =============================================

-- 1. 部門表
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID   INT          NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(50)  NOT NULL UNIQUE,
    STATUS          TINYINT      NOT NULL DEFAULT 1 COMMENT '1=啟用, 0=停用',
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID)
);

-- 2. 職等表
CREATE TABLE JOB_TITLE (
    JOB_TITLE_ID    INT          NOT NULL AUTO_INCREMENT,
    JOB_TITLE_NAME  VARCHAR(50)  NOT NULL UNIQUE,
    STATUS          TINYINT      NOT NULL DEFAULT 1 COMMENT '1=啟用, 0=停用',
    CONSTRAINT PK_JOB_TITLE PRIMARY KEY (JOB_TITLE_ID)
);

-- 3. 員工表
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID       INT          NOT NULL AUTO_INCREMENT,
    DEPARTMENT_ID     INT          NOT NULL,
    EMPLOYEE_NAME     VARCHAR(50)  NOT NULL,
    EMPLOYEE_MAIL     VARCHAR(100) NOT NULL UNIQUE,
    EMPLOYEE_PASSWORD VARCHAR(255) NOT NULL,
    PHONE             VARCHAR(20)  NOT NULL,
    ADDRESS           VARCHAR(255),
    JOB_TITLE_ID      INT          NOT NULL,
    GENDER            ENUM('M','F','OTHER') NOT NULL,
    STATUS            TINYINT      NOT NULL DEFAULT 1 COMMENT '1=在職, 0=離職',
    HIRE_DATE         DATE         NOT NULL,
    LAST_LOGIN_TIME   DATETIME,
    CONSTRAINT PK_EMPLOYEE    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_EMP_DEPT    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
    CONSTRAINT FK_EMP_JOBTITLE FOREIGN KEY (JOB_TITLE_ID) REFERENCES JOB_TITLE(JOB_TITLE_ID)
);
