-- =============================================
-- 內容模組
-- NEWS → ARTICLE → REVIEW
-- =============================================

-- ----------------------------
-- 1. 最新消息表
-- ----------------------------
CREATE TABLE NEWS (
    NEWS_ID    INT          NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(255) NOT NULL,
    CONTENT    LONGTEXT     NOT NULL,
    VIEW_COUNT INT          NOT NULL DEFAULT 0,
    STATUS     TINYINT      NOT NULL DEFAULT 1  COMMENT '1=發布, 0=下架',
    CREATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_NEWS PRIMARY KEY (NEWS_ID)
);

-- ----------------------------
-- 2. 文章表
-- ----------------------------
CREATE TABLE ARTICLE (
    ARTICLE_ID  INT          NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID INT          NOT NULL,
    CATEGORY    VARCHAR(100) NOT NULL,
    TITLE       VARCHAR(255) NOT NULL,
    CONTENT     TEXT         NOT NULL,
    COVER_IMAGE VARCHAR(500) NOT NULL COMMENT '儲存圖片路徑／URL',
    VIEW_COUNT  INT          NOT NULL DEFAULT 0,
    STATUS      TINYINT      NOT NULL DEFAULT 1  COMMENT '1=發布, 0=下架（軟刪除）',
    CREATE_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ARTICLE PRIMARY KEY (ARTICLE_ID),
    CONSTRAINT FK_ART_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- ----------------------------
-- 3. 文章評論表
-- 前提：MEMBER 表須在此之前建立
-- ----------------------------
CREATE TABLE REVIEW (
    REVIEW_ID  INT      NOT NULL AUTO_INCREMENT,
    ARTICLE_ID INT      NOT NULL,
    MEMBER_ID  INT      NOT NULL,
    CONTENT    TEXT     NOT NULL,
    LIKE_COUNT INT      NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_REVIEW  PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REV_ART FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID),
    CONSTRAINT FK_REV_MEM FOREIGN KEY (MEMBER_ID)  REFERENCES MEMBER(MEMBER_ID)
);
