USE aaaa;

-- =============================================
-- 清除舊表（順序：子表 → 父表）
-- =============================================
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS NEWS;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS EMPLOYEE;

-- =============================================
-- 1. EMPLOYEE（stub，之後再補欄位）
-- =============================================
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

-- =============================================
-- 2. MEMBER
-- =============================================
CREATE TABLE MEMBER (
    MEMBER_ID      INT          NOT NULL AUTO_INCREMENT,
    USERNAME       VARCHAR(50)  NOT NULL UNIQUE,
    EMAIL          VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD       VARCHAR(255) NOT NULL COMMENT '儲存 hashed password',
    FULL_NAME      VARCHAR(100) NOT NULL,
    PHONE          VARCHAR(20),
    GENDER         TINYINT               COMMENT '0=女 1=男 2=其他',
    BIRTHDAY       DATE,
    ADDRESS        VARCHAR(255),
    AVATAR         VARCHAR(500)          COMMENT '頭像路徑／URL',
    POINT          INT          NOT NULL DEFAULT 0 COMMENT '會員點數',
    STATUS         TINYINT      NOT NULL DEFAULT 1 COMMENT '1=正常 0=停用',
    EMAIL_VERIFIED TINYINT      NOT NULL DEFAULT 0 COMMENT '1=已驗證',
    CREATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)
);

-- =============================================
-- 3. NEWS
-- =============================================
CREATE TABLE NEWS (
    NEWS_ID    INT          NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(255) NOT NULL,
    CONTENT    LONGTEXT     NOT NULL,
    VIEW_COUNT INT          NOT NULL DEFAULT 0,
    STATUS     TINYINT      NOT NULL DEFAULT 1 COMMENT '1=發布, 0=下架',
    CREATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_NEWS PRIMARY KEY (NEWS_ID)
);

-- =============================================
-- 4. ARTICLE（依賴 EMPLOYEE）
-- =============================================
CREATE TABLE ARTICLE (
    ARTICLE_ID  INT          NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID INT          NOT NULL,
    CATEGORY    VARCHAR(100) NOT NULL,
    TITLE       VARCHAR(255) NOT NULL,
    CONTENT     TEXT         NOT NULL,
    COVER_IMAGE VARCHAR(500) NOT NULL COMMENT '儲存圖片路徑／URL',
    VIEW_COUNT  INT          NOT NULL DEFAULT 0,
    STATUS      TINYINT      NOT NULL DEFAULT 1 COMMENT '1=發布, 0=下架（軟刪除）',
    CREATE_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ARTICLE PRIMARY KEY (ARTICLE_ID),
    CONSTRAINT FK_ART_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- =============================================
-- 5. REVIEW（依賴 ARTICLE + MEMBER）
-- =============================================
CREATE TABLE REVIEW (
    REVIEW_ID  INT      NOT NULL AUTO_INCREMENT,
    ARTICLE_ID INT      NOT NULL,
    MEMBER_ID  INT      NOT NULL,
    CONTENT    TEXT     NOT NULL,
    LIKE_COUNT INT      NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_REVIEW  PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REV_ART FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID),
    CONSTRAINT FK_REV_MEM FOREIGN KEY (MEMBER_ID)  REFERENCES MEMBER(MEMBER_ID)
);
