-- ============================================================
--  Schema: Hotel Management System
--  順序：先建無外來鍵的表，再建有 FK 的表
-- ============================================================
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS NEWS;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS JOB_TITLE;
DROP TABLE IF EXISTS DEPARTMENT;
-- 1. DEPARTMENT
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID   INT          NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(50)  NOT NULL,
    STATUS          TINYINT      NOT NULL DEFAULT 1 COMMENT '1=啟用, 0=停用',
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (DEPARTMENT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. JOB_TITLE
CREATE TABLE JOB_TITLE (
    JOB_TITLE_ID   INT         NOT NULL AUTO_INCREMENT,
    JOB_TITLE_NAME VARCHAR(50) NOT NULL,
    STATUS         TINYINT     NOT NULL DEFAULT 1 COMMENT '1=啟用, 0=停用',
    CONSTRAINT PK_JOB_TITLE PRIMARY KEY (JOB_TITLE_ID),
    CONSTRAINT UQ_JOB_TITLE_NAME UNIQUE (JOB_TITLE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. EMPLOYEE  (refs DEPARTMENT, JOB_TITLE)
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID     INT          NOT NULL AUTO_INCREMENT,
    DEPARTMENT_ID   INT          NOT NULL,
    EMPLOYEE_NAME   VARCHAR(50)  NOT NULL,
    EMPLOYEE_MAIL   VARCHAR(100) NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR(255) NOT NULL,
    PHONE           VARCHAR(20)  NOT NULL,
    ADDRESS         VARCHAR(255),
    JOB_TITLE_ID    INT          NOT NULL,           -- 對齊 JOB_TITLE PK 型別
    GENDER          ENUM('M','F','OTHER') NOT NULL,  -- ENUM 須給合法值域
    STATUS          TINYINT      NOT NULL DEFAULT 1 COMMENT '1=在職, 0=離職',
    HIRE_DATE       DATE         NOT NULL,
    LAST_LOGIN_TIME DATETIME,
    CONSTRAINT PK_EMPLOYEE  PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UQ_EMPLOYEE_MAIL UNIQUE (EMPLOYEE_MAIL),
    CONSTRAINT FK_EMP_DEPT  FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT(DEPARTMENT_ID),
    CONSTRAINT FK_EMP_JOB   FOREIGN KEY (JOB_TITLE_ID)
        REFERENCES JOB_TITLE(JOB_TITLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. MEMBER  (REVIEW 的 FK 來源，需先建立)
CREATE TABLE MEMBER (
    MEMBER_ID       INT          NOT NULL AUTO_INCREMENT,
    MEMBER_NAME     VARCHAR(50)  NOT NULL,
    MEMBER_MAIL     VARCHAR(100) NOT NULL,
    MEMBER_PASSWORD VARCHAR(255) NOT NULL,
    PHONE           VARCHAR(20),
    GENDER          ENUM('M','F','OTHER'),
    STATUS          TINYINT      NOT NULL DEFAULT 1 COMMENT '1=啟用, 0=停用',
    CREATED_AT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
                                 ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_MAIL UNIQUE (MEMBER_MAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. NEWS  (無外來鍵)
CREATE TABLE NEWS (
    NEWS_ID    INT       NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(255) NOT NULL,
    CONTENT    LONGTEXT  NOT NULL,
    VIEW_COUNT INT       NOT NULL DEFAULT 0,
    STATUS     TINYINT   NOT NULL DEFAULT 1 COMMENT '1=發布, 0=下架',
    CREATED_AT DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP
                         ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_NEWS PRIMARY KEY (NEWS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. ARTICLE  (refs EMPLOYEE)
CREATE TABLE ARTICLE (
    ARTICLE_ID   INT          NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID  INT          NOT NULL,
    CATEGORY     VARCHAR(100) NOT NULL,
    VIEW_COUNT   INT          NOT NULL DEFAULT 0,
    STATUS       TINYINT      NOT NULL,
    CONTENT      TEXT         NOT NULL,
    COVER_IMAGE  LONGBLOB     NOT NULL,
    TITLE        VARCHAR(255) NOT NULL,
    CREATE_AT    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
                              ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ARTICLE PRIMARY KEY (ARTICLE_ID),
    CONSTRAINT FK_ARTICLE_EMP FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. REVIEW  (refs ARTICLE, MEMBER)
CREATE TABLE REVIEW (
    REVIEW_ID  INT      NOT NULL AUTO_INCREMENT,
    ARTICLE_ID INT      NOT NULL,
    CONTENT    TEXT     NOT NULL,
    LIKE_COUNT INT      NOT NULL DEFAULT 0,
    MEMBER_ID  INT      NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                        ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_ARTICLE FOREIGN KEY (ARTICLE_ID)
        REFERENCES ARTICLE(ARTICLE_ID),
    CONSTRAINT FK_REVIEW_MEMBER  FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
